+incdir+./includes
+incdir+./rtl
./includes/riscv_pkg.sv
./includes/drac_pkg.sv
./includes/def_pkg.sv
./rtl/datapath.sv
./rtl/if_stage/branch_predictor.sv
./rtl/if_stage/bimodal_predictor.sv
./rtl/if_stage/if_stage_1.sv
./rtl/if_stage/if_stage_2.sv
./rtl/top_drac.sv
./rtl/rr_stage/regfile.sv
./rtl/csr_interface.sv
./rtl/id_stage/immediate.sv
./rtl/id_stage/decoder.sv
./rtl/control_unit.sv
./rtl/register.sv
./rtl/exe_stage/branch_unit.sv
./rtl/exe_stage/div_unit.sv
./rtl/exe_stage/mul_unit.sv
./rtl/exe_stage/exe_stage.sv
./rtl/exe_stage/alu.sv
./rtl/exe_stage/div_4bits.sv
./rtl/exe_stage/mem_unit.sv
./rtl/exe_stage/branch_prediction_checker.sv
./rtl/csr_bsc/rtl/csr_bsc.sv
./rtl/csr_bsc/rtl/hpm_counters.sv